apiVersion: apps/v1
kind: Deployment
metadata:
  name: argomusic-deployment
  labels:
    app: argomusic-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argomusic-deployment
      tier: backend
  template:
    metadata:
      labels:
        app: argomusic-deployment
        tier: backend
    spec:
      containers:
      - name: argomusic-deployment
        image: harbor.180.210.80.52.nip.io:443/p-admin-harbor/argomusic:1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits: 
            memory: "1Gi" 
            cpu: "500m"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: image-registry-login
