---
kind: Service
apiVersion: v1
metadata:
  name: springmusic
  labels:
    app: springmusic
    tier: backend
spec:
  type: NodePort
  selector:
    app: springmusic
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: springmusic
